### ISSUE TITLE
Actividad 3. Cuadro comparativo- Adriana Hernandez Martinez  1BS

### ISSUE THREAD

**Issue by AdriHernandez-Martinez0863** [SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-AdriHernandez-Martinez0863#1]
Actividad 3. Cuadro comparativo- Metodo cientifico.pdf…]()

**Comment by AdriHernandez-Martinez0863** [comment]
Actividad 3. Cuadro comparativo
Adriana Hernandez Martinez      1BS
Actividad 3. Cuadro comparativo- Metodo cientifico.pdf…]()

**Comment by AdriHernandez-Martinez0863** [comment]
Actividad 3. Cuadro Comparativo
Adriana Hernandez Martinez        1BS
[Actividad 3. Cuadro comparativo- Metodo cientifico.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-AdriHernandez-Martinez0863/files/9458607/Actividad.3.Cuadro.comparativo-.Metodo.cientifico.pdf)

**Comment by Jaczibeth** [comment]
de 20% sacaste un 18.4%

**Comment by josealfredo79** [comment]
BIen hecho y revisado..
